using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using MvcMusicStore.Models;

namespace MvcMusicStore.Models
{
    public class SampleData : DropCreateDatabaseIfModelChanges<MusicStoreEntities>
    {
        protected override void Seed(MusicStoreEntities context)
        {
            var generos = new List<Genero>
            {
                new Genero{ Name = "Rock" },
                new Genero { Name = "Jazz" },
                new Genero { Name = "Metal" },
                new Genero { Name = "Alternative" },
                new Genero { Name = "Disco" },
                new Genero { Name = "Blues" },
                new Genero { Name = "Latin" },
                new Genero { Name = "Reggae" },
                new Genero { Name = "Pop" },
                new Genero { Name = "Classical" }
            };
            generos.ForEach(a => context.genero.Add(a));


            var artists = new List<Artista>
            {
                new Artista { Name = "Aaron Copland & London Symphony Orchestra" },
                new Artista { Name = "Aaron Goldberg" },
                new Artista { Name = "AC/DC" },
                new Artista { Name = "Accept" },
                new Artista { Name = "Adrian Leaper & Doreen de Feis" },
                new Artista { Name = "Aerosmith" },
                new Artista { Name = "Aisha Duo" },
                new Artista { Name = "Alanis Morissette" },
                new Artista { Name = "Alberto Turco & Nova Schola Gregoriana" },
                new Artista { Name = "Alice In Chains" },
                new Artista { Name = "Amy Winehouse" },
                new Artista { Name = "Anita Ward" },
                new Artista { Name = "Antônio Carlos Jobim" },
                new Artista { Name = "Apocalyptica" },
                new Artista { Name = "Audioslave" },
                new Artista { Name = "Barry Wordsworth & BBC Concert Orchestra" },
                new Artista { Name = "Berliner Philharmoniker & Hans Rosbaud" },
                new Artista { Name = "Berliner Philharmoniker & Herbert Von Karajan" },
                new Artista { Name = "Billy Cobham" },
                new Artista { Name = "Black Label Society" },
                new Artista { Name = "Black Sabbath" },
                new Artista { Name = "Boston Symphony Orchestra & Seiji Ozawa" },
                new Artista { Name = "Britten Sinfonia, Ivor Bolton & Lesley Garrett" },
                new Artista { Name = "Bruce Dickinson" },
                new Artista { Name = "Buddy Guy" },
                new Artista { Name = "Caetano Veloso" },
                new Artista { Name = "Cake" },
                new Artista { Name = "Calexico" },
                new Artista { Name = "Cássia Eller" },
                new Artista { Name = "Chic" },
                new Artista { Name = "Chicago Symphony Orchestra & Fritz Reiner" },
                new Artista { Name = "Chico Buarque" },
                new Artista { Name = "Chico Science & Nação Zumbi" },
                new Artista { Name = "Choir Of Westminster Abbey & Simon Preston" },
                new Artista { Name = "Chris Cornell" },
                new Artista { Name = "Christopher O'Riley" },
                new Artista { Name = "Cidade Negra" },
                new Artista { Name = "Cláudio Zoli" },
                new Artista { Name = "Creedence Clearwater Revival" },
                new Artista { Name = "David Coverdale" },
                new Artista { Name = "Deep Purple" },
                new Artista { Name = "Dennis Chambers" },
                new Artista { Name = "Djavan" },
                new Artista { Name = "Donna Summer" },
                new Artista { Name = "Dread Zeppelin" },
                new Artista { Name = "Ed Motta" },
                new Artista { Name = "Edo de Waart & San Francisco Symphony" },
                new Artista { Name = "Elis Regina" },
                new Artista { Name = "English Concert & Trevor Pinnock" },
                new Artista { Name = "Eric Clapton" },
                new Artista { Name = "Eugene Ormandy" },
                new Artista { Name = "Faith No More" },
                new Artista { Name = "Falamansa" },
                new Artista { Name = "Foo Fighters" },
                new Artista { Name = "Frank Zappa & Captain Beefheart" },
                new Artista { Name = "Fretwork" },
                new Artista { Name = "Funk Como Le Gusta" },
                new Artista { Name = "Gerald Moore" },
                new Artista { Name = "Gilberto Gil" },
                new Artista { Name = "Godsmack" },
                new Artista { Name = "Gonzaguinha" },
                new Artista { Name = "Göteborgs Symfoniker & Neeme Järvi" },
                new Artista { Name = "Guns N' Roses" },
                new Artista { Name = "Gustav Mahler" },
                new Artista { Name = "Incognito" },
                new Artista { Name = "Iron Maiden" },
                new Artista { Name = "James Levine" },
                new Artista { Name = "Jamiroquai" },
                new Artista { Name = "Jimi Hendrix" },
                new Artista { Name = "Joe Satriani" },
                new Artista { Name = "Jorge Ben" },
                new Artista { Name = "Jota Quest" },
                new Artista { Name = "Judas Priest" },
                new Artista { Name = "Julian Bream" },
                new Artista { Name = "Kent Nagano and Orchestre de l'Opéra de Lyon" },
                new Artista { Name = "Kiss" },
                new Artista { Name = "Led Zeppelin" },
                new Artista { Name = "Legião Urbana" },
                new Artista { Name = "Lenny Kravitz" },
                new Artista { Name = "Les Arts Florissants & William Christie" },
                new Artista { Name = "London Symphony Orchestra & Sir Charles Mackerras" },
                new Artista { Name = "Luciana Souza/Romero Lubambo" },
                new Artista { Name = "Lulu Santos" },
                new Artista { Name = "Marcos Valle" },
                new Artista { Name = "Marillion" },
                new Artista { Name = "Marisa Monte" },
                new Artista { Name = "Martin Roscoe" },
                new Artista { Name = "Maurizio Pollini" },
                new Artista { Name = "Mela Tenenbaum, Pro Musica Prague & Richard Kapp" },
                new Artista { Name = "Men At Work" },
                new Artista { Name = "Metallica" },
                new Artista { Name = "Michael Tilson Thomas & San Francisco Symphony" },
                new Artista { Name = "Miles Davis" },
                new Artista { Name = "Milton Nascimento" },
                new Artista { Name = "Mötley Crüe" },
                new Artista { Name = "Motörhead" },
                new Artista { Name = "Nash Ensemble" },
                new Artista { Name = "Nicolaus Esterhazy Sinfonia" },
                new Artista { Name = "Nirvana" },
                new Artista { Name = "O Terço" },
                new Artista { Name = "Olodum" },
                new Artista { Name = "Orchestra of The Age of Enlightenment" },
                new Artista { Name = "Os Paralamas Do Sucesso" },
                new Artista { Name = "Ozzy Osbourne" },
                new Artista { Name = "Page & Plant" },
                new Artista { Name = "Paul D'Ianno" },
                new Artista { Name = "Pearl Jam" },
                new Artista { Name = "Pink Floyd" },
                new Artista { Name = "Queen" },
                new Artista { Name = "R.E.M." },
                new Artista { Name = "Raul Seixas" },
                new Artista { Name = "Red Hot Chili Peppers" },
                new Artista { Name = "Roger Norrington, London Classical Players" },
                new Artista { Name = "Royal Philharmonic Orchestra & Sir Thomas Beecham" },
                new Artista { Name = "Rush" },
                new Artista { Name = "Santana" },
                new Artista { Name = "Scholars Baroque Ensemble" },
                new Artista { Name = "Scorpions" },
                new Artista { Name = "Sergei Prokofiev & Yuri Temirkanov" },
                new Artista { Name = "Sir Georg Solti & Wiener Philharmoniker" },
                new Artista { Name = "Skank" },
                new Artista { Name = "Soundgarden" },
                new Artista { Name = "Spyro Gyra" },
                new Artista { Name = "Stevie Ray Vaughan & Double Trouble" },
                new Artista { Name = "Stone Temple Pilots" },
                new Artista { Name = "System Of A Down" },
                new Artista { Name = "Temple of the Dog" },
                new Artista { Name = "Terry Bozzio, Tony Levin & Steve Stevens" },
                new Artista { Name = "The 12 Cellists of The Berlin Philharmonic" },
                new Artista { Name = "The Black Crowes" },
                new Artista { Name = "The Cult" },
                new Artista { Name = "The Doors" },
                new Artista { Name = "The King's Singers" },
                new Artista { Name = "The Police" },
                new Artista { Name = "The Posies" },
                new Artista { Name = "The Rolling Stones" },
                new Artista { Name = "The Who" },
                new Artista { Name = "Tim Maia" },
                new Artista { Name = "Ton Koopman" },
                new Artista { Name = "U2" },
                new Artista { Name = "UB40" },
                new Artista { Name = "Van Halen" },
                new Artista { Name = "Various Artists" },
                new Artista { Name = "Velvet Revolver" },
                new Artista { Name = "Vinícius De Moraes" },
                new Artista { Name = "Wilhelm Kempff" },
                new Artista { Name = "Yehudi Menuhin" },
                new Artista { Name = "Yo-Yo Ma" },
                new Artista { Name = "Zeca Pagodinho" }
            };

            artists.ForEach(a => context.Artista.Add(a));

            new List<Album>
            {
                new Album { Title = "The Best Of Men At Work", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Men At Work"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "A Copland Celebration, Vol. I", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Aaron Copland & London Symphony Orchestra"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Worlds", Genero = generos.Single(g => g.Name == "Jazz"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Aaron Goldberg"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "For Those About To Rock We Salute You", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "AC/DC"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Let There Be Rock", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "AC/DC"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Balls to the Wall", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Accept"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Restless and Wild", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Accept"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Górecki: Symphony No. 3", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Adrian Leaper & Doreen de Feis"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Big Ones", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Aerosmith"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Quiet Songs", Genero = generos.Single(g => g.Name == "Jazz"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Aisha Duo"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Jagged Little Pill", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Alanis Morissette"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Facelift", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Alice In Chains"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Frank", Genero = generos.Single(g => g.Name == "Pop"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Amy Winehouse"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Ring My Bell", Genero = generos.Single(g => g.Name == "Disco"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Anita Ward"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Chill: Brazil (Disc 2)", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Antônio Carlos Jobim"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Warner 25 Anos", Genero = generos.Single(g => g.Name == "Jazz"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Antônio Carlos Jobim"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Plays Metallica By Four Cellos", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Apocalyptica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Revelations", Genero = generos.Single(g => g.Name == "Alternative"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Audioslave"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Audioslave", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Audioslave"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Last Night of the Proms", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Barry Wordsworth & BBC Concert Orchestra"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Sibelius: Finlandia", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Berliner Philharmoniker & Hans Rosbaud"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Mozart: Symphonies Nos. 40 & 41", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Berliner Philharmoniker & Herbert Von Karajan"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Best Of Billy Cobham", Genero = generos.Single(g => g.Name == "Jazz"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Billy Cobham"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Alcohol Fueled Brewtality Live! [Disc 1]", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Black Label Society"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Alcohol Fueled Brewtality Live! [Disc 2]", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Black Label Society"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Black Sabbath Vol. 4 (Remaster)", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Black Sabbath"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Black Sabbath", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Black Sabbath"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Carmina Burana", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Boston Symphony Orchestra & Seiji Ozawa"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "A Soprano Inspired", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Britten Sinfonia, Ivor Bolton & Lesley Garrett"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Chemical Wedding", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Bruce Dickinson"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Prenda Minha", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Caetano Veloso"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Sozinho Remix Ao Vivo", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Caetano Veloso"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Cake: B-Sides and Rarities", Genero = generos.Single(g => g.Name == "Alternative"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Cake"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Carried to Dust (Bonus Track Version)", Genero = generos.Single(g => g.Name == "Alternative"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Calexico"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Cássia Eller - Sem Limite [Disc 1]", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Cássia Eller"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Le Freak", Genero = generos.Single(g => g.Name == "Disco"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Chic"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Scheherazade", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Chicago Symphony Orchestra & Fritz Reiner"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Minha Historia", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Chico Buarque"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Afrociberdelia", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Chico Science & Nação Zumbi"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Da Lama Ao Caos", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Chico Science & Nação Zumbi"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Carry On", Genero = generos.Single(g => g.Name == "Alternative"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Chris Cornell"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "SCRIABIN: Vers la flamme", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Christopher O'Riley"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Acústico MTV [Live]", Genero = generos.Single(g => g.Name == "Reggae"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Cidade Negra"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Cidade Negra - Hits", Genero = generos.Single(g => g.Name == "Reggae"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Cidade Negra"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Na Pista", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Cláudio Zoli"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Chronicle, Vol. 1", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Creedence Clearwater Revival"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Chronicle, Vol. 2", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Creedence Clearwater Revival"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Into The Light", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "David Coverdale"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Come Taste The Band", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Deep Purple In Rock", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Fireball", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Machine Head", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "MK III The Final Concerts [Disc 1]", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Purpendicular", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Slaves And Masters", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Stormbringer", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Battle Rages On", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Final Concerts (Disc 2)", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Deep Purple"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Outbreak", Genero = generos.Single(g => g.Name == "Jazz"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Dennis Chambers"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Djavan Ao Vivo - Vol. 02", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Djavan"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Djavan Ao Vivo - Vol. 1", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Djavan"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "MacArthur Park Suite", Genero = generos.Single(g => g.Name == "Disco"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Donna Summer"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Un-Led-Ed", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Dread Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Best of Ed Motta", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Ed Motta"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Adams, John: The Chairman Dances", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Edo de Waart & San Francisco Symphony"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Elis Regina-Minha História", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Elis Regina"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Pachelbel: Canon & Gigue", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "English Concert & Trevor Pinnock"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Unplugged", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Eric Clapton"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Cream Of Clapton", Genero = generos.Single(g => g.Name == "Blues"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Eric Clapton"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Unplugged", Genero = generos.Single(g => g.Name == "Blues"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Eric Clapton"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Respighi:Pines of Rome", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Eugene Ormandy"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Strauss: Waltzes", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Eugene Ormandy"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "King For A Day Fool For A Lifetime", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Faith No More"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Deixa Entrar", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Falamansa"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "In Your Honor [Disc 1]", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Foo Fighters"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "In Your Honor [Disc 2]", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Foo Fighters"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Colour And The Shape", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Foo Fighters"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Bongo Fury", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Frank Zappa & Captain Beefheart"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Roda De Funk", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Funk Como Le Gusta"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Quanta Gente Veio Ver (Live)", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Gilberto Gil"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Quanta Gente Veio ver--Bônus De Carnaval", Genero = generos.Single(g => g.Name == "Jazz"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Gilberto Gil"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Faceless", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Godsmack"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Meus Momentos", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Gonzaguinha"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Nielsen: The Six Symphonies", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Göteborgs Symfoniker & Neeme Järvi"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Appetite for Destruction", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Guns N' Roses"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Use Your Illusion I", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Guns N' Roses"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Use Your Illusion II", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Guns N' Roses"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Blue Moods", Genero = generos.Single(g => g.Name == "Jazz"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Incognito"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "A Matter of Life and Death", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Brave New World", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Fear Of The Dark", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Live At Donington 1992 (Disc 1)", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Live At Donington 1992 (Disc 2)", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Rock In Rio [CD2]", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Number of The Beast", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The X Factor", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Virtual XI", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "A Real Dead One", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "A Real Live One", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Live After Death", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "No Prayer For The Dying", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Piece Of Mind", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Powerslave", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Rock In Rio [CD1]", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Rock In Rio [CD2]", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Seventh Son of a Seventh Son", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Somewhere in Time", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Number of The Beast", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Iron Maiden", Genero = generos.Single(g => g.Name == "Blues"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Iron Maiden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Mascagni: Cavalleria Rusticana", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "James Levine"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Emergency On Planet Earth", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Jamiroquai"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Are You Experienced?", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Jimi Hendrix"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Surfing with the Alien (Remastered)", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Joe Satriani"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Jorge Ben Jor 25 Anos", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Jorge Ben"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Jota Quest-1995", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Jota Quest"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Living After Midnight", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Judas Priest"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Weill: The Seven Deadly Sins", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Kent Nagano and Orchestre de l'Opéra de Lyon"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Greatest Kiss", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Kiss"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Unplugged [Live]", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Kiss"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "BBC Sessions [Disc 1] [Live]", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "BBC Sessions [Disc 2] [Live]", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Coda", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Houses Of The Holy", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "In Through The Out Door", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "IV", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Led Zeppelin I", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Led Zeppelin II", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Led Zeppelin III", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Physical Graffiti [Disc 1]", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Physical Graffiti [Disc 2]", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Presence", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Song Remains The Same (Disc 1)", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Song Remains The Same (Disc 2)", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Led Zeppelin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Mais Do Mesmo", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Legião Urbana"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Greatest Hits", Genero = generos.Single(g => g.Name == "Reggae"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Lenny Kravitz"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Greatest Hits", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Lenny Kravitz"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Greatest Hits", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Lenny Kravitz"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Tchaikovsky: The Nutcracker", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "London Symphony Orchestra & Sir Charles Mackerras"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Duos II", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Luciana Souza/Romero Lubambo"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Chill: Brazil (Disc 1)", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Marcos Valle"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Misplaced Childhood", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Marillion"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Barulhinho Bom", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Marisa Monte"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Szymanowski: Piano Works, Vol. 1", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Martin Roscoe"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "...And Justice For All", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Black Album", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Garage Inc. (Disc 1)", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Garage Inc. (Disc 2)", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Load", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Master Of Puppets", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "ReLoad", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Ride The Lightning", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "St. Anger", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Metallica"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Berlioz: Symphonie Fantastique", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Michael Tilson Thomas & San Francisco Symphony"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Prokofiev: Romeo & Juliet", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Michael Tilson Thomas & San Francisco Symphony"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Miles Ahead", Genero = generos.Single(g => g.Name == "Jazz"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Miles Davis"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Essential Miles Davis [Disc 1]", Genero = generos.Single(g => g.Name == "Jazz"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Miles Davis"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Essential Miles Davis [Disc 2]", Genero = generos.Single(g => g.Name == "Jazz"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Miles Davis"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Milton Nascimento Ao Vivo", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Milton Nascimento"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Minas", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Milton Nascimento"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Motley Crue Greatest Hits", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Mötley Crüe"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Ace Of Spades", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Motörhead"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Mozart: Chamber Music", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Nash Ensemble"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Best of Beethoven", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Nicolaus Esterhazy Sinfonia"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Nevermind", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Nirvana"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Compositores", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "O Terço"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Olodum", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Olodum"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Bach: The Brandenburg Concertos", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Orchestra of The Age of Enlightenment"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Acústico MTV", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Os Paralamas Do Sucesso"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Arquivo II", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Os Paralamas Do Sucesso"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Arquivo Os Paralamas Do Sucesso", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Os Paralamas Do Sucesso"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Tribute", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Ozzy Osbourne"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Bark at the Moon (Remastered)", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Ozzy Osbourne"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Blizzard of Ozz", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Ozzy Osbourne"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Diary of a Madman (Remastered)", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Ozzy Osbourne"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "No More Tears (Remastered)", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Ozzy Osbourne"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Speak of the Devil", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Ozzy Osbourne"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Walking Into Clarksdale", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Page & Plant"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Beast Live", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Paul D'Ianno"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Live On Two Legs [Live]", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Pearl Jam"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Riot Act", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Pearl Jam"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Ten", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Pearl Jam"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Vs.", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Pearl Jam"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Dark Side Of The Moon", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Pink Floyd"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Greatest Hits I", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Queen"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Greatest Hits II", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Queen"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "News Of The World", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Queen"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "New Adventures In Hi-Fi", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "R.E.M."), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Raul Seixas", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Raul Seixas"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "By The Way", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Red Hot Chili Peppers"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Californication", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Red Hot Chili Peppers"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Purcell: The Fairy Queen", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Roger Norrington, London Classical Players"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Haydn: Symphonies 99 - 104", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Royal Philharmonic Orchestra & Sir Thomas Beecham"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Retrospective I (1974-1980)", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Rush"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Santana - As Years Go By", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Santana"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Santana Live", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Santana"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Supernatural", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Santana"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Handel: The Messiah (Highlights)", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Scholars Baroque Ensemble"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Prokofiev: Symphony No.1", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Sergei Prokofiev & Yuri Temirkanov"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Wagner: Favourite Overtures", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Sir Georg Solti & Wiener Philharmoniker"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Maquinarama", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Skank"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "O Samba Poconé", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Skank"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "A-Sides", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Soundgarden"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Heart of the Night", Genero = generos.Single(g => g.Name == "Jazz"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Spyro Gyra"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Morning Dance", Genero = generos.Single(g => g.Name == "Jazz"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Spyro Gyra"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "In Step", Genero = generos.Single(g => g.Name == "Blues"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Stevie Ray Vaughan & Double Trouble"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Core", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Stone Temple Pilots"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Mezmerize", Genero = generos.Single(g => g.Name == "Metal"), Price = 8.99M, Artist = artists.Single(a => a.Name == "System Of A Down"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Temple of the Dog", Genero = generos.Single(g => g.Name == "Alternative"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Temple of the Dog"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "[1997] Black Light Syndrome", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Terry Bozzio, Tony Levin & Steve Stevens"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "South American Getaway", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "The 12 Cellists of The Berlin Philharmonic"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Live [Disc 1]", Genero = generos.Single(g => g.Name == "Blues"), Price = 8.99M, Artist = artists.Single(a => a.Name == "The Black Crowes"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Live [Disc 2]", Genero = generos.Single(g => g.Name == "Blues"), Price = 8.99M, Artist = artists.Single(a => a.Name == "The Black Crowes"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Beyond Good And Evil", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "The Cult"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Doors", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "The Doors"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "English Renaissance", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "The King's Singers"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Police Greatest Hits", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "The Police"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Every Kind of Light", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "The Posies"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Hot Rocks, 1964-1971 (Disc 1)", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "The Rolling Stones"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "No Security", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "The Rolling Stones"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Voodoo Lounge", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "The Rolling Stones"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "My Generation - The Very Best Of The Who", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "The Who"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Serie Sem Limite (Disc 1)", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Tim Maia"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Serie Sem Limite (Disc 2)", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Tim Maia"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Bach: Toccata & Fugue in D Minor", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Ton Koopman"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Achtung Baby", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "U2"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "B-Sides 1980-1990", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "U2"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "How To Dismantle An Atomic Bomb", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "U2"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Pop", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "U2"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Rattle And Hum", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "U2"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Best Of 1980-1990", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "U2"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "War", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "U2"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Zooropa", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "U2"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "UB40 The Best Of - Volume Two [UK]", Genero = generos.Single(g => g.Name == "Reggae"), Price = 8.99M, Artist = artists.Single(a => a.Name == "UB40"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Diver Down", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Van Halen"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "The Best Of Van Halen, Vol. I", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Van Halen"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Van Halen III", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Van Halen"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Van Halen", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Van Halen"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Axé Bahia 2001", Genero = generos.Single(g => g.Name == "Pop"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Various Artists"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Sambas De Enredo 2001", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Various Artists"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Vozes do MPB", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Various Artists"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Contraband", Genero = generos.Single(g => g.Name == "Rock"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Velvet Revolver"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Vinicius De Moraes", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Vinícius De Moraes"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Bach: Goldberg Variations", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Wilhelm Kempff"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Bartok: Violin & Viola Concertos", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Yehudi Menuhin"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Bach: The Cello Suites", Genero = generos.Single(g => g.Name == "Classical"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Yo-Yo Ma"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
                new Album { Title = "Ao Vivo [IMPORT]", Genero = generos.Single(g => g.Name == "Latin"), Price = 8.99M, Artist = artists.Single(a => a.Name == "Zeca Pagodinho"), AlbumArtUrl = "/Content/Images/placeholder.gif" },
            }.ForEach(a => context.Albums.Add(a));
            context.SaveChanges();
        }
    }
}